### ISSUE TITLE
one line, two manipulations

### ISSUE THREAD

**Issue by johnnypacia** [johnnypacia/lab-shylockbot#3]
Still trying to create and append an li in one line. Here's what I have: 

var $prompt = $('#prompt');
	var $log = $('#log'); 

	var $keyPrompt = $prompt.on('keypress', function (e) {
    	var key = e.which || e.keyCode;
    	if (key === 13) { $('<li>').$log($('li')); }
		});

I get an error on the second to last line, saying $log is not a function (this happens even if I change the name), but the keypress works if I replace it with a console.log. Any leads on how to resolve this issue?

**Comment by johnnypacia** [comment]
@sungchoi @annarankin still stuck on this...I hear phil stepped out for a second.

**Comment by annarankin** [comment]
Hey Johnny, side note - I see you're setting the variable `$keyPrompt` equal to the return value of calling `.on()` on `$prompt`. What are you expecting that to return?

When it comes to your .$log is not a function error - let's break it down:
`$('<li>').$log($('li'));`
- First, `$('<li>')` creates a new li element.
- Next, `.$log()` causes JS to throw a "not a function" error, since `$log` is a jQuery object, not a method defined on our jQuery objects. 
- Inside of those parentheses, I see you've got `$('li')`, which will return a jQuery object containing all li's currently on the DOM. Is that what you were expecting?

**Comment by phlco** [comment]
Hi I was in a sample teach, but it looks like @annarankin is laying it down!
